# try_e_except.py